export enum UserRegisterStepsEnum {
  FIRST_INTERACTION = 'FIRST_INTERACTION',
  ASK_IF_IS_CUSTOMER = 'ASK_IF_IS_CUSTOMER',
  ASK_NAME = 'ASK_NAME',
  ASK_CNPJ = 'ASK_CNPJ',
  REGISTERED = 'REGISTERED',
}
